-- =====================================================
-- PRIVATE CHEF - SUPABASE SCHEMA
-- =====================================================
-- This schema supports the Private Chef application
-- with public access for bookings and chef signups
-- =====================================================

-- =====================================================
-- TABLES
-- =====================================================

-- Bookings Table
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    date TEXT NOT NULL,
    guests INTEGER NOT NULL,
    service_type TEXT NOT NULL CHECK (service_type IN ('chef', 'box')),
    duration INTEGER,
    cuisine TEXT,
    selected_menu TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Christmas Chefs Applications Table
CREATE TABLE IF NOT EXISTS public.christmas_chefs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    experience INTEGER,
    email TEXT NOT NULL,
    portfolio TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Menu Items Table (Optional - can use static data in frontend instead)
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    chef_name TEXT,
    price TEXT,
    image_url TEXT,
    description TEXT,
    courses JSONB,
    category TEXT DEFAULT 'box',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Cuisines Table (Optional - can use static data in frontend instead)
CREATE TABLE IF NOT EXISTS public.cuisines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- ROW LEVEL SECURITY (RLS)
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.christmas_chefs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cuisines ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- RLS POLICIES
-- =====================================================

-- Bookings: Allow public insert, authenticated read
CREATE POLICY "Allow public to insert bookings"
ON public.bookings
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read bookings"
ON public.bookings
FOR SELECT
TO authenticated
USING (true);

-- Christmas Chefs: Allow public insert, authenticated read
CREATE POLICY "Allow public to insert chef applications"
ON public.christmas_chefs
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read chef applications"
ON public.christmas_chefs
FOR SELECT
TO authenticated
USING (true);

-- Menu Items: Public read access
CREATE POLICY "Allow public to read menu items"
ON public.menu_items
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow authenticated users to manage menu items"
ON public.menu_items
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Cuisines: Public read access
CREATE POLICY "Allow public to read cuisines"
ON public.cuisines
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Allow authenticated users to manage cuisines"
ON public.cuisines
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- =====================================================
-- STORAGE BUCKETS
-- =====================================================

-- Create storage bucket for images
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policy: Allow public uploads
CREATE POLICY "Allow public uploads"
ON storage.objects
FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'images');

-- Storage policy: Allow public reads
CREATE POLICY "Allow public reads"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'images');

-- =====================================================
-- SEED DATA (Optional)
-- =====================================================

-- Insert sample cuisines
INSERT INTO public.cuisines (name, image_url) VALUES
('Italian', 'https://images.unsplash.com/photo-1498579150354-977475b7ea0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'),
('French', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'),
('Asian', 'https://images.unsplash.com/photo-1541544744-cc81127adbdd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'),
('Vegan', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80'),
('Seafood', 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80')
ON CONFLICT DO NOTHING;

-- Insert sample menu items
INSERT INTO public.menu_items (title, chef_name, price, image_url, description, courses, category) VALUES
(
    'Christmas 4-course',
    'Bergpaviljoen Bistronomique',
    '€64,50 p.p.',
    'https://images.unsplash.com/photo-1544025162-d7669d045862?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    'Classic Christmas menu with traditional flavors',
    '[
        {"name": "Amuse Loembia", "desc": "Crispy duck confit, hoisin glaze, pickled cucumber."},
        {"name": "Lobster Bisque", "desc": "Rich cognac cream, chives, brioche croutons, chili oil."},
        {"name": "Rouleau of Pheasant", "desc": "Sauerkraut, truffle gravy, caramelized apple, potato mousseline."},
        {"name": "Grand Dessert", "desc": "Dark chocolate mousse, salted caramel, gold leaf, hazelnut praline."}
    ]'::jsonb,
    'box'
),
(
    'Brut172 Christmas',
    'Hans Van Wolde',
    '€99,50 p.p.',
    'https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    'Premium Christmas experience',
    '[
        {"name": "King Crab & Caviar", "desc": "Lemon gel, dill emulsion, crispy quinoa."},
        {"name": "Wild Boar Stew", "desc": "Slow-cooked in red wine, roasted root vegetables, puff pastry."},
        {"name": "Venison Steak", "desc": "Blackberry jus, parsnip puree, roasted brussels sprouts."},
        {"name": "Floating Island", "desc": "Vanilla creme anglaise, spun sugar, almond crunch."}
    ]'::jsonb,
    'box'
),
(
    'Ron Gastrobar',
    'Ron Blaauw',
    '€31,00 p.p.',
    'https://images.unsplash.com/photo-1512485800893-b08ec1ea59b1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    'Casual fine dining experience',
    '[
        {"name": "Tuna Tataki", "desc": "Sesame crust, wasabi mayo, soy reduction."},
        {"name": "Indonesian Rendang", "desc": "Coconut beef curry, fluffy white rice, sambal beans."},
        {"name": "Passionfruit Cheesecake", "desc": "Cookie crumble, mango sorbet, mint."}
    ]'::jsonb,
    'box'
)
ON CONFLICT DO NOTHING;

-- =====================================================
-- INDEXES (Performance Optimization)
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_bookings_created_at ON public.bookings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chefs_created_at ON public.christmas_chefs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_menu_items_category ON public.menu_items(category);

-- =====================================================
-- NOTES
-- =====================================================
-- 
-- To use this schema:
-- 1. Create a new Supabase project at https://supabase.com
-- 2. Go to SQL Editor in your Supabase dashboard
-- 3. Copy and paste this entire file
-- 4. Click "Run" to execute
-- 5. Get your project URL and anon key from Settings > API
-- 6. Add them to your .env file in the React app
--
-- =====================================================
